-- ============================================
-- MIGRATION COMPLETA - TODOS OS CAMPOS DO CLIENTE (MariaDB) PARA LEAD (PostgreSQL)
-- Arquivo: migration_cliente_complete.sql
-- Database: zioncrm (PostgreSQL - IP 45.160.180.34)
-- Origem: ixcprovedor (MariaDB - IP 45.160.180.14)
-- ============================================

-- ADICIONAR CAMPOS BÁSICOS (se não existirem)
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id SERIAL PRIMARY KEY;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS razao VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS fantasia VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS endereco VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS numero VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS bairro VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cidade INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS uf INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cnpj_cpf VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ie_identidade VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cond_pagamento INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS fone VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cep VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS email VARCHAR(256);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(1) DEFAULT 'F';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_tipo_cliente INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ativo VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_conta INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_internet VARCHAR(2) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS bloqueio_automatico VARCHAR(1);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS aviso_atraso VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS obs TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS dia_vencimento INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_myauth INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS telefone_comercial VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS telefone_celular VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS referencia VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS complemento VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ramal VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS senha VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nao_bloquear_ate DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nao_avisar_ate DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_vendedor INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS isuf VARCHAR(9);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_assinante VARCHAR(1) DEFAULT '3';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS contato VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS hotsite_email VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS hotsite_acesso INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS filial_id INTEGER DEFAULT 1;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS latitude VARCHAR(50);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS longitude VARCHAR(50);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_candato_tipo INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tabela_preco INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS rg_orgao_emissor VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(30) DEFAULT 'Brasileiro';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS deb_automatico VARCHAR(25);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS deb_agencia VARCHAR(10);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS deb_conta VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS alerta TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_cadastro DATE;

-- ENDEREÇO DE COBRANÇA
ALTER TABLE lead ADD COLUMN IF NOT EXISTS endereco_cob VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS numero_cob VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS bairro_cob VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cidade_cob INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS uf_cob INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cep_cob VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS referencia_cob VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS complemento_cob VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS participa_cobranca VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS num_dias_cob INTEGER;

-- DADOS PROFISSIONAIS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS profissao VARCHAR(50);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS url_site TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS url_sistema TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ip_sistema VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS porta_ssh_sistema INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS senha_root_sistema VARCHAR(100);

-- CONFIGURAÇÕES DE COBRANÇA
ALTER TABLE lead ADD COLUMN IF NOT EXISTS remessa_debito INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_operadora_celular INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS participa_pre_cobranca VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cob_envia_email VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cob_envia_sms VARCHAR(1) DEFAULT 'S';

-- DADOS FISCAIS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS contribuinte_icms VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS iss_classificacao VARCHAR(2) DEFAULT '99';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS iss_classificacao_padrao VARCHAR(2) DEFAULT '99';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_cliente_scm VARCHAR(10) DEFAULT '01';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS pis_retem VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cofins_retem VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS csll_retem VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS irrf_retem VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS inss_retem VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS inscricao_municipal VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS regime_fiscal_col VARCHAR(2);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cli_desconta_iss_retido_total VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS desconto_irrf_valor_inferior VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_ente_governamental VARCHAR(1);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS percentual_reducao DECIMAL(7,4);

-- DADOS PESSOAIS E FAMILIARES
ALTER TABLE lead ADD COLUMN IF NOT EXISTS sexo VARCHAR(3);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_condominio INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_pai VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_mae VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS quantidade_dependentes INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_conjuge VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS fone_conjuge VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cpf_conjuge VARCHAR(15);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS rg_conjuge VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_nascimento_conjuge DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS moradia VARCHAR(1);

-- DADOS DO CONTADOR
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_contador VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS telefone_contador VARCHAR(20);

-- REFERÊNCIAS COMERCIAIS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_com_empresa1 VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_com_empresa2 VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_com_fone1 VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_com_fone2 VARCHAR(20);

-- REFERÊNCIAS PESSOAIS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_pes_nome1 VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_pes_nome2 VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_pes_fone1 VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ref_pes_fone2 VARCHAR(20);

-- DADOS DE EMPREGO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_empresa VARCHAR(150);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_cnpj VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_cep VARCHAR(15);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_endereco VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_cidade INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_fone VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_contato VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_cargo VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_remuneracao DECIMAL(15,2);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS emp_data_admissao DATE;

-- REDES SOCIAIS E CONTATO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS website VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS skype VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS facebook VARCHAR(250);

-- PROSPECÇÃO E VENDAS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_prospeccao VARCHAR(2) DEFAULT 'C';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS prospeccao_ultimo_contato DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS prospeccao_proximo_contato DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS substatus_prospeccao INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS orgao_publico VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS pipe_id_organizacao INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS grau_satisfacao VARCHAR(1);

-- LOCALIZAÇÃO ADICIONAL
ALTER TABLE lead ADD COLUMN IF NOT EXISTS im VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS responsavel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS bloco VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS apartamento VARCHAR(11);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cif VARCHAR(12);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS idx INTEGER;

-- DOCUMENTOS ADICIONAIS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cpf_pai VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cpf_mae VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS identidade_pai VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS identidade_mae VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nascimento_pai DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nascimento_mae DATE;

-- REPRESENTANTES
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_representante_1 VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_representante_2 VARCHAR(200);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cpf_representante_1 VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cpf_representante_2 VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS identidade_representante_1 VARCHAR(30);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS identidade_representante_2 VARCHAR(30);

-- RELACIONAMENTOS E INTEGRAÇÕES
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_contato_principal INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_concorrente INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_perfil INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS codigo_operacao INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS convert_cliente_forn VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_canal_venda INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_campanha INTEGER;

-- DÉBITO/PAGAMENTO AUTOMÁTICO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_pessoa_titular_conta VARCHAR(1) DEFAULT 'F';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cnpj_cpf_titular_conta VARCHAR(30);

-- INTEGRAÇÕES EXTERNAS
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cadastrado_no_galaxPay VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS atualizar_cadastro_galaxPay VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_galaxPay INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_vindi INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS yapay_token_account VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS permite_armazenar_cartoes VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS foto_cartao BYTEA;

-- TV E STREAMING
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tv_code TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tv_access_token TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tv_token_expires_in TIMESTAMP;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tv_refresh_token TEXT;

-- ACESSO E SEGURANÇA
ALTER TABLE lead ADD COLUMN IF NOT EXISTS acesso_automatico_central VARCHAR(1) DEFAULT 'P';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS primeiro_acesso_central VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS alterar_senha_primeiro_acesso VARCHAR(1) DEFAULT 'P';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS hash_redefinir_senha VARCHAR(32);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_hash_redefinir_senha TIMESTAMP;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS senha_hotsite_md5 VARCHAR(1) DEFAULT 'N';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS antigo_acesso_central VARCHAR(1) DEFAULT 'N';

-- SERASA E ANÁLISE DE CRÉDITO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ativo_serasa INTEGER;

-- VIABILIDADE E CONTRATAÇÃO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_vd_contrato_desejado INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cadastrado_via_viabilidade VARCHAR(1);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_viabilidade VARCHAR(1);

-- TIPO DE LOCALIDADE E VELOCIDADE
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_localidade VARCHAR(1) DEFAULT 'U';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS qtd_pessoas_calc_vel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS qtd_smart_calc_vel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS qtd_celular_calc_vel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS qtd_computador_calc_vel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS qtd_console_calc_vel INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS freq_pessoas_calc_vel VARCHAR(7);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS freq_smart_calc_vel VARCHAR(7);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS freq_celular_calc_vel VARCHAR(7);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS freq_computador_calc_vel VARCHAR(7);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS freq_console_calc_vel VARCHAR(7);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS resultado_calc_vel VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_cobranca_auto_viab INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS plano_negociacao_auto_viab INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_reserva_auto_viab DATE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS melhor_periodo_reserva_auto_viab VARCHAR(1);

-- NATURALIDADE
ALTER TABLE lead ADD COLUMN IF NOT EXISTS cidade_naturalidade INTEGER;

-- OPERAÇÃO E REDE
ALTER TABLE lead ADD COLUMN IF NOT EXISTS operador_neutro INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_rede VARCHAR(1);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS rede_ativacao VARCHAR(1) DEFAULT 'P';

-- IDENTIFICAÇÃO EXTERNA
ALTER TABLE lead ADD COLUMN IF NOT EXISTS external_id VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS external_system VARCHAR(50);

-- INDICAÇÃO E CONVERSÃO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS indicado_por INTEGER;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS numero_antigo VARCHAR(40);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS numero_cob_antigo VARCHAR(40);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_fornecedor_conversao INTEGER;

-- FILIAL E SEGMENTO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS filtra_filial VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS id_segmento INTEGER;

-- DOCUMENTAÇÃO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS tipo_documento_identificacao VARCHAR(4) DEFAULT '13';

-- RÉGUA DE COBRANÇA
ALTER TABLE lead ADD COLUMN IF NOT EXISTS regua_cobranca_wpp VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS regua_cobranca_notificacao VARCHAR(1) DEFAULT 'S';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS regua_cobranca_considera VARCHAR(1) DEFAULT 'P';

-- NOME SOCIAL
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nome_social VARCHAR(200);

-- TIMESTAMP DE ATUALIZAÇÃO
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ultima_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- CAMPOS DE CLASSIFICAÇÃO (já existentes na migration anterior)
ALTER TABLE lead ADD COLUMN IF NOT EXISTS prioridade VARCHAR(50) DEFAULT 'NovaLead';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_vendas VARCHAR(50) DEFAULT 'NovaLeadVendas';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_pos_venda VARCHAR(100);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS nivel_contentamento VARCHAR(20);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS status_debito VARCHAR(20) DEFAULT 'EmDia';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS origem VARCHAR(50);
ALTER TABLE lead ADD COLUMN IF NOT EXISTS departamento VARCHAR(20) DEFAULT 'vendas';
ALTER TABLE lead ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS obs_classificacao TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS data_ultima_classificacao TIMESTAMP;

-- CRIAR ÍNDICES PARA MELHOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_lead_cnpj_cpf ON lead(cnpj_cpf);
CREATE INDEX IF NOT EXISTS idx_lead_email ON lead(email);
CREATE INDEX IF NOT EXISTS idx_lead_fone ON lead(fone);
CREATE INDEX IF NOT EXISTS idx_lead_razao ON lead(razao);
CREATE INDEX IF NOT EXISTS idx_lead_fantasia ON lead(fantasia);
CREATE INDEX IF NOT EXISTS idx_lead_ativo ON lead(ativo);
CREATE INDEX IF NOT EXISTS idx_lead_prioridade ON lead(prioridade);
CREATE INDEX IF NOT EXISTS idx_lead_status_vendas ON lead(status_vendas);
CREATE INDEX IF NOT EXISTS idx_lead_departamento ON lead(departamento);
CREATE INDEX IF NOT EXISTS idx_lead_origem ON lead(origem);
CREATE INDEX IF NOT EXISTS idx_lead_score ON lead(score);
CREATE INDEX IF NOT EXISTS idx_lead_data_cadastro ON lead(data_cadastro);
CREATE INDEX IF NOT EXISTS idx_lead_ultima_atualizacao ON lead(ultima_atualizacao);
CREATE INDEX IF NOT EXISTS idx_lead_cidade ON lead(cidade);
CREATE INDEX IF NOT EXISTS idx_lead_id_vendedor ON lead(id_vendedor);
CREATE INDEX IF NOT EXISTS idx_lead_telefone_celular ON lead(telefone_celular);
CREATE INDEX IF NOT EXISTS idx_lead_whatsapp ON lead(whatsapp);

-- COMENTÁRIOS EXPLICATIVOS
COMMENT ON COLUMN lead.razao IS 'Nome ou razão social do cliente';
COMMENT ON COLUMN lead.fantasia IS 'Nome fantasia do cliente';
COMMENT ON COLUMN lead.cnpj_cpf IS 'CNPJ ou CPF do cliente';
comment ON COLUMN lead.tipo_pessoa IS 'Tipo de pessoa: F=Física, J=Jurídica';
COMMENT ON COLUMN lead.prioridade IS 'Temperatura da lead: NovaLead, Ruim, Fria, Morna, Quente, MuitoQuente, Queimando';
COMMENT ON COLUMN lead.status_vendas IS 'Status no processo de vendas';
COMMENT ON COLUMN lead.departamento IS 'Departamento responsável: vendas ou pos_venda';
COMMENT ON COLUMN lead.score IS 'Pontuação da lead (0-100)';
COMMENT ON COLUMN lead.ativo IS 'S=Ativo, N=Inativo';

-- VERIFICAR COLUNAS CRIADAS
SELECT column_name, data_type, character_maximum_length, column_default
FROM information_schema.columns
WHERE table_name = 'lead'
ORDER BY ordinal_position;

-- MIGRATION COMPLETA ✅
